export enum ActionType {
  SET_AUDIO_BLOB = "SET_AUDIO_PATH",
  SET_SUBTITLE_TEXT = "SET_SUBTITLE_TEXT",
  SET_SUBTITLE_ARRAY = "SET_SUBTITLE_ARRAY",
  SET_CURRENT_TIME = "SET_CURRENT_TIME",
  SET_NEW_TIME = "SET_NEW_TIME",
}
